"""Shared reporting-opportunity stream definitions."""

STREAM_COMPONENTS: tuple[tuple[str, str | None], ...] = (
    ("PHYSICAL_VIEWABILITY", None),
    ("POPULATION_TRAVEL_OPPORTUNITY", "POPULATION_TRAVEL_OPPORTUNITY_INDEX"),
    ("ROAD_ACCESS_OPPORTUNITY", "ROAD_PROXIMITY_COMPONENT"),
    ("CITY_ACCESS_OPPORTUNITY", "CITY_TRAVEL_ACCESS_COMPONENT"),
    ("TRANSPORT_ACCESS_OPPORTUNITY", "LAND_TRANSPORT_ACCESS_OPPORTUNITY_INDEX"),
    ("LAND_REACHABILITY_OPPORTUNITY", "LAND_TRANSPORT_TRAVEL_OPPORTUNITY_INDEX"),
    ("LAND_EFFORT_PROXY", "MAPPED_PUBLIC_ACCESS_SUPPORTED_INDEX"),
    ("VERIFIED_LAND_EFFORT_PROXY", "VERIFIED_PUBLIC_ACCESS_SUPPORTED_INDEX"),
)

HUMAN_STREAMS = tuple(name for name, component in STREAM_COMPONENTS if component is not None)
PRIMARY_STREAM = "LAND_EFFORT_PROXY"
